### ISSUE TITLE
sefer faturalandırma ekranında sefer eksik geliyor

### ISSUE THREAD

**Issue by makro4242** [makro4242/nkly#15]
sefer faturalandırma ekranında sefer eksik geliyor.... tamamlanmış 5 seferimiz var ama fatura ekranına 1 tanesi geliyor

**Comment by zizoumurat** [comment]
seferlere girilen cariler , lokasyon cari fiyat tanıtım kartında tanımlanmadığı için kayıtlar gelmiyor.
